language : node_js
node_js :
  - "8.9.3"

script :
   - npm install
   - npm run build

install :
   - npm install -g firebase-tools

after_success :
   - firebase deploy --project san2beerelli-2e39c --token $FIREBASE_TOKEN